### PR TITLE
Merge failed event

### PR DESCRIPTION
**Pull request by dpursehouse**
I did this on top of the previous pull request #41, so that one should be merged first, or this one will include both commits.

### CODE REVIEW

**Comment by rsandell** [comment]
this pr contains both new events

**Comment by dpursehouse** [comment]
Doesn't it merge if the previous one is already merged?  If not I'll rebase
it.

**Comment by rsandell** [comment]
Well it's just that if there is a need to revert the other one the code will still be there.

**Comment by dpursehouse** [comment]
The events are added in separate commits. It should still be possible to
revert either of them.

**Pull request merged**
