### PR TITLE
Adding ability for external json config file to ignore incoming events

### PR DESCRIPTION
**Pull request by MattLud**

### CODE REVIEW

**Comment by MattLud** [comment]
I should add a doc change for this as well before merging.

**Comment by MattLud** [comment]
Added small doc change. Merge or advise how next steps.

**Comment by rsandell** [comment]
Thanks! I'll try to get this released today.

**Comment by rsandell** [comment]
Sonatype had some stability issues on Friday, but I managed to release it this morning.

**Pull request merged**
