### PR TITLE
Added methods to get a read only view of registered listeners

### PR DESCRIPTION
**Pull request by rsandell**

### CODE REVIEW

**Comment by rsandell** [comment]
Can @reviewbybees see this?

**Comment by oleg-nenashev** [comment]
LGTM :bee:

**Comment by jtnord** [comment]
LGTMT :bee:

**Comment by rsandell** [comment]
I'm just holding on to the merge while I'm testing against the snapshot locally.

**Comment by rsandell** [comment]
@reviewbybees done

**Pull request merged**
